export const chartAnalyticsTheme = {
  colors: {
    canvas: "var(--theme-color-canvas)",
    surface: "var(--theme-color-surface)",
    card: "var(--theme-color-card)",
    textPrimary: "var(--theme-color-text-primary)",
    textMuted: "var(--theme-color-text-muted)",
    textSubtle: "var(--theme-color-text-subtle)",
    textInverse: "var(--theme-color-text-inverse)",
    stroke: "var(--theme-color-stroke)",
    strokeSoft: "var(--theme-color-stroke-soft)",
    grid: "var(--theme-color-grid)",
    darkCanvas: "var(--theme-color-dark-canvas)",
    darkPanel: "var(--theme-color-dark-panel)",
    darkText: "var(--theme-color-dark-text)",
    darkMutedText: "var(--theme-color-dark-muted-text)",
    darkBorder: "var(--theme-color-dark-border)",
    darkCallout: "var(--theme-color-dark-callout)",
    signalPrimary: "var(--theme-color-signal-primary)",
    signalPrimaryTint: "var(--theme-color-signal-primary-tint)",
    signalPrimaryBorder: "var(--theme-color-signal-primary-border)",
    signalSecondary: "var(--theme-color-signal-secondary)",
    signalSecondaryTint: "var(--theme-color-signal-secondary-tint)",
    signalSecondaryBorder: "var(--theme-color-signal-secondary-border)",
    signalTertiary: "var(--theme-color-signal-tertiary)",
    signalTertiaryTint: "var(--theme-color-signal-tertiary-tint)",
    signalTertiaryBorder: "var(--theme-color-signal-tertiary-border)",
    signalRisk: "var(--theme-color-signal-risk)",
    signalRiskTint: "var(--theme-color-signal-risk-tint)",
    signalRiskBorder: "var(--theme-color-signal-risk-border)",
    signalWarning: "var(--theme-color-signal-warning)",
    signalWarningTint: "var(--theme-color-signal-warning-tint)",
    signalWarningBorder: "var(--theme-color-signal-warning-border)",
    signalSuccess: "var(--theme-color-signal-success)",
    signalSuccessTint: "var(--theme-color-signal-success-tint)",
    signalSuccessBorder: "var(--theme-color-signal-success-border)",
    signalNeutral: "var(--theme-color-signal-neutral)",
    signalNeutralTint: "var(--theme-color-signal-neutral-tint)",
    signalNeutralBorder: "var(--theme-color-signal-neutral-border)",
    entityPrimary: "var(--theme-color-entity-primary)",
    entityPrimaryTint: "var(--theme-color-entity-primary-tint)",
    entityPrimaryBorder: "var(--theme-color-entity-primary-border)",
    entitySecondary: "var(--theme-color-entity-secondary)",
    entitySecondaryTint: "var(--theme-color-entity-secondary-tint)",
    entitySecondaryBorder: "var(--theme-color-entity-secondary-border)",
    chart1: "var(--theme-color-chart-1)",
    chart2: "var(--theme-color-chart-2)",
    chart3: "var(--theme-color-chart-3)",
    chart4: "var(--theme-color-chart-4)",
    chart5: "var(--theme-color-chart-5)",
    chart6: "var(--theme-color-chart-6)",
    chartStructureSegment1: "var(--theme-color-chart-structure-segment-1)",
    chartStructureSegment2: "var(--theme-color-chart-structure-segment-2)",
    chartStructureSegment3: "var(--theme-color-chart-structure-segment-3)",
  },
  fonts: {
    body: 'var(--body-font-family,Roboto,Inter,"Noto Sans SC",sans-serif)',
    display: 'var(--display-font-family,Montserrat,Inter,"Noto Sans SC",sans-serif)',
  },
  shadows: {
    card: "var(--theme-shadow-card)",
    panel: "var(--theme-shadow-panel)",
    darkPanel: "var(--theme-shadow-dark-panel)",
    soft: "var(--theme-shadow-soft)",
  },
  palette: {
    chart: [
      "var(--theme-color-chart-1)",
      "var(--theme-color-chart-2)",
      "var(--theme-color-chart-3)",
      "var(--theme-color-chart-4)",
      "var(--theme-color-chart-5)",
      "var(--theme-color-chart-6)",
    ],
    structure: [
      "var(--theme-color-chart-structure-segment-1)",
      "var(--theme-color-chart-structure-segment-2)",
      "var(--theme-color-chart-structure-segment-3)",
    ],
  },
  tone: {
    signalPrimary: {
      color: "var(--theme-color-signal-primary)",
      tint: "var(--theme-color-signal-primary-tint)",
      border: "var(--theme-color-signal-primary-border)",
    },
    signalSecondary: {
      color: "var(--theme-color-signal-secondary)",
      tint: "var(--theme-color-signal-secondary-tint)",
      border: "var(--theme-color-signal-secondary-border)",
    },
    signalTertiary: {
      color: "var(--theme-color-signal-tertiary)",
      tint: "var(--theme-color-signal-tertiary-tint)",
      border: "var(--theme-color-signal-tertiary-border)",
    },
    signalRisk: {
      color: "var(--theme-color-signal-risk)",
      tint: "var(--theme-color-signal-risk-tint)",
      border: "var(--theme-color-signal-risk-border)",
    },
    signalWarning: {
      color: "var(--theme-color-signal-warning)",
      tint: "var(--theme-color-signal-warning-tint)",
      border: "var(--theme-color-signal-warning-border)",
    },
    signalSuccess: {
      color: "var(--theme-color-signal-success)",
      tint: "var(--theme-color-signal-success-tint)",
      border: "var(--theme-color-signal-success-border)",
    },
    signalNeutral: {
      color: "var(--theme-color-signal-neutral)",
      tint: "var(--theme-color-signal-neutral-tint)",
      border: "var(--theme-color-signal-neutral-border)",
    },
    entityPrimary: {
      color: "var(--theme-color-entity-primary)",
      tint: "var(--theme-color-entity-primary-tint)",
      border: "var(--theme-color-entity-primary-border)",
    },
    entitySecondary: {
      color: "var(--theme-color-entity-secondary)",
      tint: "var(--theme-color-entity-secondary-tint)",
      border: "var(--theme-color-entity-secondary-border)",
    },
  },
  alpha: {
    darkCanvas: (opacity: number) => `rgba(var(--theme-color-dark-canvas-rgb), ${opacity})`,
    darkPanel: (opacity: number) => `rgba(var(--theme-color-dark-panel-rgb), ${opacity})`,
    signalPrimary: (opacity: number) => `rgba(var(--theme-color-signal-primary-rgb), ${opacity})`,
    signalSecondary: (opacity: number) => `rgba(var(--theme-color-signal-secondary-rgb), ${opacity})`,
    textInverse: (opacity: number) => `rgba(var(--theme-color-text-inverse-rgb), ${opacity})`,
  },
} as const;

export type ChartAnalyticsTone = keyof typeof chartAnalyticsTheme.tone;
