#!/usr/bin/env python3

"""Generate an importable Python module that embeds the Executa tool manifest."""

from __future__ import annotations

import argparse
import json
import pprint
from pathlib import Path
from typing import Any


def read_tool_manifest(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in tool manifest: {path}")
    for key in ("name", "version"):
        value = payload.get(key)
        if not isinstance(value, str) or not value:
            raise ValueError(f"Tool manifest must include a non-empty {key}: {path}")
    return payload


def render_module(manifest: dict[str, Any]) -> str:
    literal = pprint.pformat(manifest, indent=4, width=100, sort_dicts=False)
    return (
        "# Generated by scripts/embed_manifest.py. Do not edit by hand.\n"
        "# Source of truth is manifest.json; regenerate via build_binary.sh.\n"
        "\n"
        "EMBEDDED_MANIFEST = " + literal + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    manifest = read_tool_manifest(args.manifest)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_module(manifest), encoding="utf-8")
    print(f"Embedded tool manifest into {args.output}")


if __name__ == "__main__":
    main()
