import type { StabilityRule } from "../types.js";
import {
  GROUP_JSON_REQUIRED_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  LOCAL_SOURCE_PATH_RULE,
  MANIFEST_STRUCTURE_RULE,
  SHARED_MODULE_ENTRY_RULE,
} from "./manifest-rules.js";

export const STATIC_RULES: StabilityRule[] = [
  GROUP_JSON_REQUIRED_RULE,
  MANIFEST_STRUCTURE_RULE,
  LOCAL_SOURCE_PATH_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  SHARED_MODULE_ENTRY_RULE,
];

export {
  GROUP_JSON_REQUIRED_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  LOCAL_SOURCE_PATH_RULE,
  MANIFEST_STRUCTURE_RULE,
  SHARED_MODULE_ENTRY_RULE,
};
