import type { StabilityRule } from "../types.js";
import {
  GROUP_JSON_REQUIRED_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  LOCAL_SOURCE_PATH_RULE,
  MANIFEST_STRUCTURE_RULE,
  SHARED_MODULE_ENTRY_RULE,
} from "./manifest-rules.js";
import {
  FIXED_CANVAS_HINT_RULE,
  RUNTIME_DEPENDENCY_RULE,
  SCHEMA_FIELD_COVERAGE_RULE,
  SCHEMA_PARSE_RULE,
  ZOD_SCHEMA_RULE,
} from "./tsx-ast-rules.js";

export const STATIC_RULES: StabilityRule[] = [
  GROUP_JSON_REQUIRED_RULE,
  MANIFEST_STRUCTURE_RULE,
  LOCAL_SOURCE_PATH_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  ZOD_SCHEMA_RULE,
  SCHEMA_PARSE_RULE,
  SCHEMA_FIELD_COVERAGE_RULE,
  FIXED_CANVAS_HINT_RULE,
  RUNTIME_DEPENDENCY_RULE,
  SHARED_MODULE_ENTRY_RULE,
];

export {
  FIXED_CANVAS_HINT_RULE,
  GROUP_JSON_REQUIRED_RULE,
  LOCAL_MODULE_EXPORT_RULE,
  LOCAL_SOURCE_PATH_RULE,
  MANIFEST_STRUCTURE_RULE,
  RUNTIME_DEPENDENCY_RULE,
  SCHEMA_FIELD_COVERAGE_RULE,
  SCHEMA_PARSE_RULE,
  SHARED_MODULE_ENTRY_RULE,
  ZOD_SCHEMA_RULE,
};
