// This file is generated by ppt-app/scripts/sync-tool-manifests.mjs.
// Do not edit it by hand.

export const PPT_ENGINE_TOOL = {
  handle: "ppt-engine",
  version: "4.1.1",
  displayName: "ppt-engine",
} as const;

export const PPT_GENER_TOOL = {
  handle: "ppt-gener",
  version: "3.1.4",
  displayName: "ppt-gener",
} as const;

export const ANNA_SEARCH_TOOL = {
  handle: "anna-search",
  version: "1.0.1",
  displayName: "Anna Search",
} as const;
