export interface ThemePreset {
  theme_id: string;
  theme_name: string;
  theme_description: string;
  fit: string[];
  tone: string[];
  avoid: string[];
  data: {
    colors: Record<string, string>;
  };
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    theme_id: "finance-red-classic",
    theme_name: "Finance Red Classic",
    theme_description: "Formal red, white, and neutral palette for finance, policy, banking, and executive reports.",
    fit: ["finance", "banking", "policy", "executive-report"],
    tone: ["formal", "authoritative", "analytical"],
    avoid: ["consumer", "playful", "youth-brand"],
    data: {
      colors: {
        primary: "#B71C1C",
        background: "#FFFFFF",
        card: "#FAFAFA",
        stroke: "#E5E7EB",
        primary_text: "#FFFFFF",
        background_text: "#212121",
        secondary: "#1565C0",
        text_muted: "#616161",
        text_subtle: "#757575",
        stroke_soft: "#E0E0E0",
        axis: "#D0D0D0",
        icon_muted: "#D6D6D6",
        panel: "#FAFAFA",
        surface: "#FFFFFF",
        accent_soft: "#FFEBEE",
        accent_tint: "#FFF4F4",
        accent_border: "#F1CACA",
        accent_subtle_text: "#9D2E2E",
        primary_dark: "#8E0000",
        shadow_primary: "rgba(183,28,28,0.2)",
        row_accent: "rgba(183,28,28,0.03)",
        graph_0: "#B71C1C",
        graph_1: "#1565C0",
        graph_2: "#2E7D32",
        graph_3: "#EF6C00",
        graph_4: "#6A1B9A",
        graph_5: "#455A64",
        graph_6: "#C62828",
        graph_7: "#0277BD",
        graph_8: "#558B2F",
        graph_9: "#8D6E63",
      },
    },
  },
  {
    theme_id: "board-blue",
    theme_name: "Board Blue",
    theme_description: "Calm corporate blue palette for board updates, management reports, and investor-facing analysis.",
    fit: ["board", "investment", "management", "risk-control"],
    tone: ["credible", "restrained", "professional"],
    avoid: ["celebratory", "consumer", "high-energy-marketing"],
    data: {
      colors: {
        primary: "#0F4C81",
        background: "#FFFFFF",
        card: "#F7FAFC",
        stroke: "#D9E2EC",
        primary_text: "#FFFFFF",
        background_text: "#18212F",
        secondary: "#2F80ED",
        text_muted: "#526173",
        text_subtle: "#718096",
        stroke_soft: "#C9D6E2",
        axis: "#B8C7D8",
        icon_muted: "#AEBCCD",
        panel: "#F7FAFC",
        surface: "#FFFFFF",
        accent_soft: "#E8F1FB",
        accent_tint: "#F0F6FD",
        accent_border: "#C9DEF4",
        accent_subtle_text: "#1F5F93",
        primary_dark: "#08385F",
        shadow_primary: "rgba(15,76,129,0.18)",
        row_accent: "rgba(15,76,129,0.04)",
        graph_0: "#0F4C81",
        graph_1: "#2F80ED",
        graph_2: "#00A3A3",
        graph_3: "#7B61FF",
        graph_4: "#F2994A",
        graph_5: "#27AE60",
        graph_6: "#6B7280",
        graph_7: "#93C5FD",
        graph_8: "#99F6E4",
        graph_9: "#CBD5E1",
      },
    },
  },
  {
    theme_id: "strategy-green",
    theme_name: "Strategy Green",
    theme_description: "Measured green palette for ESG, strategy, operations, public-sector, and transformation decks.",
    fit: ["strategy", "esg", "operations", "public-sector", "transformation"],
    tone: ["steady", "constructive", "long-term"],
    avoid: ["urgent-crisis", "luxury", "entertainment"],
    data: {
      colors: {
        primary: "#1B5E20",
        background: "#FFFFFF",
        card: "#F6FAF6",
        stroke: "#D7E5D8",
        primary_text: "#FFFFFF",
        background_text: "#1F2A24",
        secondary: "#0F766E",
        text_muted: "#526458",
        text_subtle: "#718476",
        stroke_soft: "#C7D9C8",
        axis: "#B6CCB8",
        icon_muted: "#A7BBA9",
        panel: "#F6FAF6",
        surface: "#FFFFFF",
        accent_soft: "#EAF5EA",
        accent_tint: "#F1F8F1",
        accent_border: "#C8E0CA",
        accent_subtle_text: "#2D6A31",
        primary_dark: "#0E4214",
        shadow_primary: "rgba(27,94,32,0.18)",
        row_accent: "rgba(27,94,32,0.04)",
        graph_0: "#1B5E20",
        graph_1: "#2E7D32",
        graph_2: "#66A060",
        graph_3: "#0F766E",
        graph_4: "#A16207",
        graph_5: "#3F6212",
        graph_6: "#64748B",
        graph_7: "#86EFAC",
        graph_8: "#A7F3D0",
        graph_9: "#D9F99D",
      },
    },
  },
  {
    theme_id: "graphite-gold",
    theme_name: "Graphite Gold",
    theme_description: "Premium graphite and gold palette for annual reviews, wealth, consulting, and high-stakes summaries.",
    fit: ["consulting", "wealth", "annual-review", "executive-summary"],
    tone: ["premium", "confident", "polished"],
    avoid: ["dense-technical", "academic", "playful"],
    data: {
      colors: {
        primary: "#A77A22",
        background: "#FFFFFF",
        card: "#FAF8F3",
        stroke: "#E4DDCF",
        primary_text: "#FFFFFF",
        background_text: "#252525",
        secondary: "#3B3B3B",
        text_muted: "#5F5A52",
        text_subtle: "#81796B",
        stroke_soft: "#D8D0C0",
        axis: "#C5BCA9",
        icon_muted: "#B8AE9B",
        panel: "#FAF8F3",
        surface: "#FFFFFF",
        accent_soft: "#F5ECD8",
        accent_tint: "#FBF6EA",
        accent_border: "#E5D1A7",
        accent_subtle_text: "#7B5B1D",
        primary_dark: "#6D4F14",
        shadow_primary: "rgba(167,122,34,0.18)",
        row_accent: "rgba(167,122,34,0.045)",
        graph_0: "#A77A22",
        graph_1: "#3B3B3B",
        graph_2: "#6B7280",
        graph_3: "#8B5E34",
        graph_4: "#0F4C81",
        graph_5: "#7C2D12",
        graph_6: "#B0893C",
        graph_7: "#D6B56D",
        graph_8: "#C7C7C7",
        graph_9: "#E8DFC8",
      },
    },
  },
  {
    theme_id: "digital-indigo",
    theme_name: "Digital Indigo",
    theme_description: "Modern indigo palette for SaaS, AI, fintech, digital transformation, and product strategy.",
    fit: ["saas", "ai", "fintech", "digital-transformation", "product-strategy"],
    tone: ["modern", "technical", "sharp"],
    avoid: ["traditional-policy", "heritage-brand", "conservative-board"],
    data: {
      colors: {
        primary: "#4338CA",
        background: "#FFFFFF",
        card: "#F8FAFF",
        stroke: "#DDE3F5",
        primary_text: "#FFFFFF",
        background_text: "#1E1B4B",
        secondary: "#2563EB",
        text_muted: "#535C7A",
        text_subtle: "#717A9B",
        stroke_soft: "#CCD5F0",
        axis: "#B9C5E7",
        icon_muted: "#AAB6D8",
        panel: "#F8FAFF",
        surface: "#FFFFFF",
        accent_soft: "#EEF2FF",
        accent_tint: "#F5F7FF",
        accent_border: "#D5DBFF",
        accent_subtle_text: "#4338CA",
        primary_dark: "#312E81",
        shadow_primary: "rgba(67,56,202,0.18)",
        row_accent: "rgba(67,56,202,0.04)",
        graph_0: "#4338CA",
        graph_1: "#2563EB",
        graph_2: "#0891B2",
        graph_3: "#7C3AED",
        graph_4: "#DB2777",
        graph_5: "#16A34A",
        graph_6: "#475569",
        graph_7: "#A5B4FC",
        graph_8: "#BAE6FD",
        graph_9: "#DDD6FE",
      },
    },
  },
  {
    theme_id: "neutral-slate",
    theme_name: "Neutral Slate",
    theme_description: "General-purpose neutral palette for research, training, internal communication, and content-heavy decks.",
    fit: ["research", "training", "internal-communication", "general-business"],
    tone: ["quiet", "clear", "balanced"],
    avoid: ["brand-campaign", "luxury", "youthful"],
    data: {
      colors: {
        primary: "#334155",
        background: "#FFFFFF",
        card: "#F8FAFC",
        stroke: "#CBD5E1",
        primary_text: "#FFFFFF",
        background_text: "#111827",
        secondary: "#0F766E",
        text_muted: "#4B5563",
        text_subtle: "#64748B",
        stroke_soft: "#D6DEE8",
        axis: "#B8C2CF",
        icon_muted: "#AEB8C6",
        panel: "#F8FAFC",
        surface: "#FFFFFF",
        accent_soft: "#EEF2F7",
        accent_tint: "#F8FAFC",
        accent_border: "#D8E0EA",
        accent_subtle_text: "#334155",
        primary_dark: "#1E293B",
        shadow_primary: "rgba(51,65,85,0.18)",
        row_accent: "rgba(51,65,85,0.04)",
        graph_0: "#334155",
        graph_1: "#0F766E",
        graph_2: "#2563EB",
        graph_3: "#9333EA",
        graph_4: "#CA8A04",
        graph_5: "#DC2626",
        graph_6: "#64748B",
        graph_7: "#94A3B8",
        graph_8: "#C4B5FD",
        graph_9: "#BAE6FD",
      },
    },
  },
];

export const THEME_PRESET_IDS = THEME_PRESETS.map((theme) => theme.theme_id);

export function getThemePreset(themeId: string | null | undefined): ThemePreset | null {
  if (!themeId) return null;
  return THEME_PRESETS.find((theme) => theme.theme_id === themeId) ?? null;
}

export function buildThemeCatalogForPrompt() {
  return THEME_PRESETS.map((theme) => ({
    theme_id: theme.theme_id,
    name: theme.theme_name,
    description: theme.theme_description,
    fit: theme.fit,
    tone: theme.tone,
    avoid: theme.avoid,
  }));
}
