export const redFinanceTheme = {
  colors: {
    background: "var(--background-color,#FFFFFF)",
    backgroundText: "var(--background-text,#212121)",
    card: "var(--card-color,#FAFAFA)",
    primary: "var(--primary-color,#B71C1C)",
    primaryText: "var(--primary-text,#FFFFFF)",
    secondary: "var(--secondary-color,var(--graph-1,#1565C0))",
    mutedText: "var(--text-muted,#616161)",
    subtleText: "var(--text-subtle,#757575)",
    stroke: "var(--stroke,#E5E7EB)",
    softStroke: "var(--stroke-soft,#E0E0E0)",
    axis: "var(--axis-color,#D0D0D0)",
    iconMuted: "var(--icon-muted,#D6D6D6)",
    panel: "var(--panel-color,#FAFAFA)",
    surface: "var(--surface-color,#FFFFFF)",
    paleRed: "var(--accent-soft,color-mix(in srgb,var(--primary-color,#B71C1C) 10%, white))",
    accentTint: "var(--accent-tint,color-mix(in srgb,var(--primary-color,#B71C1C) 6%, white))",
    accentBorder: "var(--accent-border,#F1CACA)",
    accentSubtleText: "var(--accent-subtle-text,#9D2E2E)",
    deepRed: "var(--primary-dark,#8E0000)",
    shadowPrimary: "var(--shadow-primary,rgba(183,28,28,0.2))",
    rowAccent: "var(--row-accent,rgba(183,28,28,0.03))",
  },
  fonts: {
    body: 'var(--body-font-family,Roboto,"Noto Sans CJK SC","Noto Sans SC",sans-serif)',
  },
} as const;
