export const redFinanceTheme = {
  colors: {
    canvas: "var(--theme-color-canvas)",
    surface: "var(--theme-color-surface)",
    panel: "var(--theme-color-panel)",
    card: "var(--theme-color-card)",
    textPrimary: "var(--theme-color-text-primary)",
    textSecondary: "var(--theme-color-text-secondary)",
    textMuted: "var(--theme-color-text-muted)",
    textSubtle: "var(--theme-color-text-subtle)",
    textInverse: "var(--theme-color-text-inverse)",
    accent: "var(--theme-color-accent)",
    accentText: "var(--theme-color-accent-text)",
    accentStrong: "var(--theme-color-accent-strong)",
    accentSoft: "var(--theme-color-accent-soft)",
    accentTint: "var(--theme-color-accent-tint)",
    accentBorder: "var(--theme-color-accent-border)",
    accentMutedText: "var(--theme-color-accent-muted-text)",
    stroke: "var(--theme-color-stroke)",
    strokeSoft: "var(--theme-color-stroke-soft)",
    axis: "var(--theme-color-axis)",
    iconMuted: "var(--theme-color-icon-muted)",
    rowAccent: "var(--theme-color-row-accent)",
    chart1: "var(--theme-color-chart-1)",
    chart2: "var(--theme-color-chart-2)",
    chart3: "var(--theme-color-chart-3)",
    chart4: "var(--theme-color-chart-4)",
    chart5: "var(--theme-color-chart-5)",
    chart6: "var(--theme-color-chart-6)",
  },
  shadows: {
    card: "var(--theme-shadow-card)",
    panel: "var(--theme-shadow-panel)",
    accent: "var(--theme-shadow-accent)",
  },
  alpha: {
    canvas: (opacity: number) => `rgba(var(--theme-color-canvas-rgb), ${opacity})`,
    accent: (opacity: number) => `rgba(var(--theme-color-accent-rgb), ${opacity})`,
    textPrimary: (opacity: number) => `rgba(var(--theme-color-text-primary-rgb), ${opacity})`,
  },
  fonts: {
    body: 'var(--body-font-family,Roboto,"Noto Sans SC",sans-serif)',
  },
} as const;
