- module-name: 'presenton_sdk_pptx_generator'
  dlls:
    - from_filenames:
        relative_path: '_runtime/cairo'
        prefixes:
          - ''
        suffixes:
          - 'dll'
      dest_path: 'presenton_sdk_pptx_generator/_runtime/cairo'
    - from_filenames:
        relative_path: '_runtime/cairo'
        prefixes:
          - 'lib'
        suffixes:
          - 'dylib'
      dest_path: 'presenton_sdk_pptx_generator/_runtime/cairo'
