export const redBlueComparisonTheme = {
  size: {
    slideWidth: 1280,
    slideHeight: 720,
    contentLeft: 80,
    contentRight: 80,
    contentWidth: 1120,
    headerTop: 46,
    headerHeight: 74,
    contentTop: 156,
    footerHeight: 46,
  },
  colors: {
    canvas: "var(--theme-color-canvas)",
    surface: "var(--theme-color-surface)",
    card: "var(--theme-color-card)",
    textPrimary: "var(--theme-color-text-primary)",
    textMuted: "var(--theme-color-text-muted)",
    textSubtle: "var(--theme-color-text-subtle)",
    textInverse: "var(--theme-color-text-inverse)",
    stroke: "var(--theme-color-stroke)",
    strokeSoft: "var(--theme-color-stroke-soft)",
    grid: "var(--theme-color-grid)",
    tableGrid: "var(--theme-color-table-grid)",
    comparison: "var(--theme-color-comparison)",
    comparisonSoft: "var(--theme-color-comparison-soft)",
    comparisonTint: "var(--theme-color-comparison-tint)",
    comparisonBorder: "var(--theme-color-comparison-border)",
    sideA: "var(--theme-color-side-a)",
    sideATint: "var(--theme-color-side-a-tint)",
    sideABorder: "var(--theme-color-side-a-border)",
    sideB: "var(--theme-color-side-b)",
    sideBTint: "var(--theme-color-side-b-tint)",
    sideBBorder: "var(--theme-color-side-b-border)",
    neutral: "var(--theme-color-neutral)",
    neutralTint: "var(--theme-color-neutral-tint)",
    neutralBorder: "var(--theme-color-neutral-border)",
    statusWarning: "var(--theme-color-status-warning)",
    statusSuccess: "var(--theme-color-status-success)",
    chart1: "var(--theme-color-chart-1)",
    chart2: "var(--theme-color-chart-2)",
    chart3: "var(--theme-color-chart-3)",
    chart4: "var(--theme-color-chart-4)",
    chart5: "var(--theme-color-chart-5)",
    chart6: "var(--theme-color-chart-6)",
    chartSectorAgriculture: "var(--theme-color-chart-sector-agriculture)",
    chartSectorIndustry: "var(--theme-color-chart-sector-industry)",
    chartSectorServices: "var(--theme-color-chart-sector-services)",
    chartAgeYoung: "var(--theme-color-chart-age-young)",
    chartAgeWorking: "var(--theme-color-chart-age-working)",
    chartAgeElderly: "var(--theme-color-chart-age-elderly)",
  },
  fonts: {
    heading: 'var(--heading-font-family,Montserrat,"Noto Sans SC",sans-serif)',
    body: 'var(--body-font-family,Inter,"Noto Sans SC",sans-serif)',
  },
  radius: {
    xs: 4,
    sm: 6,
    md: 8,
    lg: 10,
    xl: 12,
    pill: 999,
  },
  border: {
    hairline: "1px solid var(--theme-color-stroke)",
    subtle: "1px solid var(--theme-color-neutral-border)",
    accent: "1px solid var(--theme-color-comparison-border)",
  },
  shadow: {
    card: "var(--theme-shadow-card)",
    panel: "var(--theme-shadow-panel)",
    soft: "var(--theme-shadow-soft)",
  },
  tone: {
    sideA: {
      color: "var(--theme-color-side-a)",
      tint: "var(--theme-color-side-a-tint)",
      border: "var(--theme-color-side-a-border)",
    },
    sideB: {
      color: "var(--theme-color-side-b)",
      tint: "var(--theme-color-side-b-tint)",
      border: "var(--theme-color-side-b-border)",
    },
    comparison: {
      color: "var(--theme-color-comparison)",
      tint: "var(--theme-color-comparison-tint)",
      border: "var(--theme-color-comparison-border)",
    },
    neutral: {
      color: "var(--theme-color-neutral)",
      tint: "var(--theme-color-neutral-tint)",
      border: "var(--theme-color-neutral-border)",
    },
  },
  alpha: {
    canvas: (opacity: number) => `rgba(var(--theme-color-canvas-rgb), ${opacity})`,
    surface: (opacity: number) => `rgba(var(--theme-color-surface-rgb), ${opacity})`,
    textPrimary: (opacity: number) => `rgba(var(--theme-color-text-primary-rgb), ${opacity})`,
    comparison: (opacity: number) => `rgba(var(--theme-color-comparison-rgb), ${opacity})`,
    sideA: (opacity: number) => `rgba(var(--theme-color-side-a-rgb), ${opacity})`,
    sideB: (opacity: number) => `rgba(var(--theme-color-side-b-rgb), ${opacity})`,
    neutral: (opacity: number) => `rgba(var(--theme-color-neutral-rgb), ${opacity})`,
  },
} as const;

export type ComparisonTone = keyof typeof redBlueComparisonTheme.tone;
